# Describes the format for available UPB scene services

link_activate:
  description: Activate a UPB scene.
  fields:
    entity_id:
      description: Name(s) of scenes to activate
      example: "scene.hygge"

link_deactivate:
  description: Deactivate a UPB scene.
  fields:
    entity_id:
      description: Name(s) of scenes to deactivate
      example: "scene.hygge"

link_goto:
  description: Set all lights in scene at brightness
  fields:
    entity_id:
      description: Name(s) of scenes to deactivate
      example: "scene.hygge"
    brightness_pct:
      description: Brightness of lights in scene from 0 to 100
      example: 42
    rate:
      description: Rate for scene to transition to new brightness
      example: 3

link_fade_start:
  description: Start fading a link.
  fields:
    entity_id:
      description: Name(s) of links to start fading
      example: "scene.party"
    brightness_pct:
      description: Brightness of link from 0 to 100
      example: 42
    rate:
      description: Rate for link to transition to new brightness
      example: 3

link_fade_stop:
  description: Stop a link fade.
  fields:
    entity_id:
      description: Name(s) of links to stop fadding
      example: "scene.dining, scene.no_tv"

link_blink:
  description: Blink a link
  fields:
    entity_id:
      description: Name(s) of links to start fading
      example: "scene.hygge"
    rate:
      description: Rate for link to blink
      example: 60

light_fade_start:
  description: Start fading a light.
  fields:
    entity_id:
      description: Name(s) of lights to start fading
      example: "light.kitchen"
    brightness_pct:
      description: Brightness of light from 0 to 100
      example: 42
    rate:
      description: Rate for light to transition to new brightness
      example: 3

light_fade_stop:
  description: Stop a light fade.
  fields:
    entity_id:
      description: Name(s) of lights to stop fadding
      example: "light.kitchen, light.family_room"

light_blink:
  description: Blink a light
  fields:
    entity_id:
      description: Name(s) of lights to start fading
      example: "light.kitchen"
    rate:
      description: Rate for light to blink
      example: 60

light_update_status:
  description: Cause a light to report its current status.
  fields:
    entity_id:
      description: Name(s) of lights to refresh their status
      example: "light.kitchen, light.family_room"
